# Generated by Django 3.2.4 on 2021-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
